spring:
  datasource:
    url: jdbc:h2:file:~/h2_data//lammy
    username: sa
    driver-class-name: org.h2.Driver
    druid:
      initialSize: 5  
      min-idle: 5
      max-active: 20  
     # 配置获取连接等待超时的时间  
      max-wait: 60000  
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒  
      time-between-eviction-runs-millis: 60000 
    # 配置一个连接在池中最小生存的时间，单位是毫秒  
      min-evictable-idle-time-millis: 300000  
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-return: false 
      test-on-borrow: false  
    # 打开PSCache，并且指定每个连接上PSCache的大小  
      pool-prepared-statements: true 
      max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙  
    # spring.datasource.filters: stat,wall,log4j  
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  h2:
    console:
      enabled: true

lammy: 
  interceptor: 
    urls:
      - /user/checkUser
      
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.peng.lammy.domain.po

logging.level.com.peng.lammy.dao: debug
  
